### DISCUSSION TITLE
How can I get more insight on the integration / more log outputs?

### DISCUSSION THREAD

**Discussion by Tom-Bom-badil** [Tom-Bom-badil/home-assistant_helios-vallox#11] [(en) FAQ]
During installation, you have put the follwoing line into you `configuration.yaml`in the HA root:

```yaml
logger:
  logs:
    custom_components.helios_vallox_ventilation: error
```

The following log levels are supported by the integration:
- **error** (default; remain silent, but log any errors + critical errors),
- **info** (also log single polls and re-reads),
- **debug** (detailed info for each poll - careful, HUGE amount of data!).

You can adjust the log level at any time by modifying above line in your configuration.yaml (requires integration reload/HA restart).
