### DISCUSSION TITLE
Setting fan speed

### DISCUSSION THREAD

**Discussion by mariokorte** [Tom-Bom-badil/home-assistant_helios-vallox#17] [(en/de) General discussions and issues]
This add on works like charm in home assistant. Thanks a lot for the helpful wiki and the project itself. I just have one question: how can the fan speed of the ventilation be changed. I see the entity, that displays the current speed, but cannot find a way to set it (or like with the remote use up and down to adjust). Am I missing something?

**Comment by Tom-Bom-badil** [comment]
You will need to call a service - that's the way HA is dealing with this. You can call services e.g. from the developer tools., or from click / hold actions in the Lovelace UI (e.g. on a button).

- go to devloper tools,
- click 'actions' tab,
- copy / paste the following and run it:

```
action: helios_vallox_ventilation.write_value
data:
  variable: fanspeed
  value: 5
```

Here an example how to use this on a custom:button-card:

```
type: custom:button-card
title: set_fanspeed_to_3
tap_action:
  action: call-service
  service: helios_vallox_ventilation.write_value
  service_data:
    variable: fanspeed
    value: 3
```

It is the same procedure for any writeable variable - just specify the name and the value. All variables are listed in `REGISTERS_AND_COILS` in `custom_components/helios_vallox_ventilation/const.py`.

By the way, with the next release I will deliver a bunch of pre-made Lovelace cards - the remote control and fanspeed buttons are already working (the remote is 1:1 interactive like the one mounted at your wall, all buttons are clickable). I am currently doing the timed fan speed (aka 'boost mode') and some gauges:

![image](https://github.com/user-attachments/assets/e29993d4-7a2b-49ab-850b-31f2d2dc7029)

2-3 more weeks till you can download those and use them on your dashboard ...

/tom
