### DISCUSSION TITLE
Works with Vallox 090SE

### DISCUSSION THREAD

**Discussion by au-ee** [Tom-Bom-badil/home-assistant_helios-vallox#22] [(en/de) General discussions and issues]
Hi,

I just wanted to tell you that I was successful.

I just got my RS485-LAN-Adapter (USR-DR134), configured it according to the wiki and wired it up to my Vallox 090SE. 
Then, I installed the plugin through HACS and a couple of seconds later, I had data in HA.

This took me about an hour and I am really excited about my new possibilities, now.

Thanks for the good work!

Markus

**Comment by Tom-Bom-badil** [comment]
Markus, thank you for the feedback, good to hear it worked out for you!
Enjoy the integration! :)

/tom

**Comment by mariokorte** [comment]
Mine's a Vallox 080SE, working like charm. 👍

**Comment by CMeinersHH** [comment]
Hi Tom, 

Just wanted to say that the package works perfectly with my Vallox KWL 090SE.

As adapter eth-RS485, I’m using a Raspberry Pi zero 2 W running Raspberry Pi OS Lite, together with a USB-RS485 stick (Waveshare) and ser2net on the Pi. That setup has been working very reliably so far and also gives some more options (firewall, troubleshooting).  

Thanks a lot for creating this great repo!

Christian

**Reply by Tom-Bom-badil** [reply]
Most welcome, Christian - glad it's working and of use for you. :)

/tom

**Comment by RayRats0** [comment]
Hi Tom

Thank for making this available.

I have it working with a Vallox Effect 150 SE.

David

**Reply by Tom-Bom-badil** [reply]
Thanks for the feedback, will update docs accordingly.
Enjoy the integration! :)

/tom

**Comment by wertzui** [comment]
Does anyone know if these are the correct configuration values for the 90SE?
I'm sure on the power values as these are clear from the manual, but for the airflow the diagram is hard to read.
I took the values from the noise-table below the diagram and added `P+T` and converted it from `dm³/s` into `m³/h`.
The table only has values for `2,4,6,8` so I took the average for the values in between.

```yaml
helios_vallox_airflow_per_mode: '0,73,145,186,227,280,334,421,509'
helios_vallox_max_airflow:      509
helios_vallox_power_per_mode:   '0,12,18,25,34,50,75,117,185'
helios_vallox_max_power:        185
helios_vallox_heating_power:    900
```

**Reply by Tom-Bom-badil** [reply]
Isn't max airflow for the 090SE at ~300 m³/h? Found a diagram here with all 8 levels (top of page 5):
https://vallox.de/wp-content/uploads/2023/09/13_TA_090SE_f_01_2012.pdf

There seems to be different airflow for fresh air (ZK1...8) and exhaust air (AK1...8). Not sure how to deal with that - maybe just take the middle. The airflow is to be interpreted with care anyways, as it differs a lot with pressure loss and amount / quality / cleanliness of filters installed.

/tom

**Reply by wertzui** [reply]
That seems to be an outdated manual from 2012.
I've got the one from here: https://www.vallox.com/en/product/vallox-90-se/
Which links to [this one](https://res.cloudinary.com/vallox/image/upload/v1694418857/FileStock/ValidManuals/KHT_Vallox90SE_ENG_20130514.pdf) from 2014.
I also have a German copy of the one from 2014 stored locally, but don't ask me where I got that one from 😄.

**Reply by wertzui** [reply]
Did a new calculation with just the exhaust air and then it's the same at `276,12 m³/h`

So these are my new values for the 90 SE:
```yaml
helios_vallox_house_area:       105
helios_vallox_house_volume:     273
helios_vallox_isolation_factor: 0.3
helios_vallox_airflow_per_mode: '0,43,86,107,129,158,187,231,276'
helios_vallox_max_airflow:      509
helios_vallox_power_per_mode:   '0,12,18,25,34,50,75,117,185'
helios_vallox_max_power:        185
helios_vallox_heating_power:    900
```
